---
# This workflow will build and deploy the documentation to GitHub Pages
name: Docs deployment

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6.0.2
      - name: 🏗 Set up UV
        uses: astral-sh/setup-uv@v7.3.1
        with:
          version: "latest"
      - name: 🏗 Install dependencies
        run: uv sync --group docs
      - name: 🏗 Build documentation
        run: uv run mkdocs build
      - name: ⬆️ Upload pages artifacts
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 🏗️ Setup Github Pages
        uses: actions/configure-pages@v5.0.0
      - name: 🚀 Deploy to Github Pages
        uses: actions/deploy-pages@v4.0.5
        id: deployment
